FROM node:16.14.2-alpine
WORKDIR /app
COPY . .

# RUN npm install
# RUN npm run build
# RUN npm install webpack-dev-server
# RUN npm run dev
ENTRYPOINT npm start
# ENTRYPOINT [ "webpack-dev-server", "--hot", "--port", "3000" ]
# ENTRYPOINT [ ".node_modules/.bin/webpack-dev-server", "--hot", "--port", "3000" ]
